name: bg_score
description: "Track and manage your Backgammon match scores easily."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  intl: ^0.20.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Launcher-Icons Generator
  flutter_launcher_icons: ^0.13.1

# Konfiguration für flutter_launcher_icons (Root-Ebene!)
flutter_launcher_icons:
  android: true
  ios: true

  # Gemeinsames Icon (PNG, 1024x1024, ohne abgerundete Ecken)
  image_path: assets/favicon3.png

  # Android Adaptive Icon (empfohlen)
  adaptive_icon_background: "#0A3C92"
  adaptive_icon_foreground: assets/favicon3.png
  adaptive_icon_monochrome: assets/favicon3.png   # optional (Android 13+)

  # iOS: Entfernt Transparenz automatisch (falls vorhanden)
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  generate: true   # <--- WICHTIG: aktiviert gen_l10n

  assets:
    - assets/favicon3.png